spring:
  datasource:
    data: "classpath:/seed/h2-seed-data.sql"
    driverClassName: "org.h2.Driver"
    url: "jdbc:h2:mem:mandants;DB_CLOSE_ON_EXIT=FALSE"
    validation-query: "SELECT 1"
    test-on-borrow: true
    test-on-return: true
    test-while-idle: true
    time-between-eviction-runs-millis: 3600
    min-evictable-idle-time-millis: 3600
  jpa:
    show-sql: true
    generate-ddl: true
  data.jpa.repositories:
    enabled: true
  h2.console.enabled: true

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
